language: java

script: ./.travis-build.sh

jdk:
  - openjdk11
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/ec3127975d8a2b8f11d0"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
after_success:
  - mvn -B test jacoco:report coveralls:report
# http://lint.travis-ci.org/ validator

jobs:
  include:
    - stage: trigger-downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
          SLUGOWNER=${TRAVIS_REPO_SLUG%/*}
          echo "SLUGOWNER=$SLUGOWNER"
          if [ -v ${TRAVIS_ACCESS_TOKEN+x} ] ; then
            echo "TRAVIS_ACCESS_TOKEN is not set" && false
          else
            sh trigger-travis.sh ${SLUGOWNER} checker-framework $TRAVIS_ACCESS_TOKEN
          fi
        fi

git:
  depth: 9
